#pragma once

#include <stdint.h>

// The push-to-talk input, as the rest of the firmware sees it.
//
// WHY THIS INTERFACE EXISTS
//
// The external SW201 button is not available yet, so development runs on the
// Core2's centre capacitive touch button. Moving to the SW201 later must be a
// CONFIGURATION change and nothing more -- no edit to the conversation state
// machine, the audio path or the face renderer. That requirement is the entire
// reason this abstraction exists, and it is why the selection lives in
// include/tth/Config.h behind TTH_PTT_INPUT rather than as #ifdefs scattered
// through the code that consumes it.
//
// Both implementations share their timing behaviour (debounce, one-shot edges,
// maximum hold) by delegating to the portable PttButton, so the two inputs
// cannot quietly drift apart.

namespace tth {

class IPushToTalkInput {
 public:
  virtual ~IPushToTalkInput() {}

  // One-time hardware setup. Safe to call once from App::begin().
  virtual void begin() = 0;

  // Sample the input. Called once per main-loop iteration, after M5.update().
  // Must never block.
  virtual void poll(uint32_t nowMs) = 0;

  // Debounced level: true while the button is genuinely held.
  virtual bool isHeld() const = 0;

  // One-shot edges. Each returns true at most once per physical event and
  // clears itself, so exactly one caller acts on each press/release.
  virtual bool consumePress() = 0;
  virtual bool consumeRelease() = 0;

  // How long the current hold has lasted, or 0 when not held.
  virtual uint32_t heldForMs(uint32_t nowMs) const = 0;

  // Duration of the most recently COMPLETED hold, in ms. Captured when the
  // release edge is generated, so it stays correct however long the caller
  // takes to consume that edge.
  virtual uint32_t lastHoldMs() const = 0;

  // True when the most recent release was generated by the maximum-hold
  // timeout rather than by the user letting go. Callers use it only for
  // reporting; the release itself is delivered identically either way.
  virtual bool lastReleaseWasForced() const = 0;

  // Human-readable identification for the startup report.
  virtual const char* name() const = 0;
};

}  // namespace tth
