// Build-time generation of the TTH Bot base prompt (PHASE6_PLAN §5.3).
//
// The canonical base prompt lives in the Flutter app:
//   lib/core/prompts/edubot_base_prompt.dart  (const eduBotBasePrompt = '''...''')
//
// This script extracts it ONCE, at build time, into
//   gateway/src/generated/edubot_base_prompt.ts
// so the running gateway never parses Dart. tests/prompt_parity_test.ts fails
// if the generated file no longer matches the Dart source.
//
// Deliberately strict: anything beyond a plain '''...''' literal — string
// interpolation ($), escapes (\), raw or adjacent strings — makes this FAIL,
// so a change to the prompt's syntax is reviewed instead of mistranslated.
//
//   deno task generate

export const DART_PROMPT_PATH = "../lib/core/prompts/edubot_base_prompt.dart";
export const GENERATED_PATH = "src/generated/edubot_base_prompt.ts";
export const DART_CONSTANT = "eduBotBasePrompt";

export function extractDartTripleQuoted(source: string, name: string): string {
  const marker = `const String ${name} = '''`;
  const start = source.indexOf(marker);
  if (start < 0) throw new Error(`'${marker}' not found`);
  if (source.indexOf(marker, start + marker.length) >= 0) {
    throw new Error(`'${name}' is declared twice`);
  }
  const rest = source.slice(start + marker.length);
  const end = rest.indexOf("'''");
  if (end < 0) throw new Error("unterminated ''' literal");
  if (!/^\s*;/.test(rest.slice(end + 3))) {
    throw new Error("unsupported: the literal is not followed directly by ';'");
  }
  let body = rest.slice(0, end);
  if (body.includes("$")) throw new Error("unsupported: string interpolation ($)");
  if (body.includes("\\")) throw new Error("unsupported: escape sequence (\\)");
  // Windows checkouts may carry CRLF; the prompt content is the same text.
  body = body.replace(/\r\n/g, "\n");
  // Dart drops a first line that holds only whitespace after the opening '''.
  const firstNewline = body.indexOf("\n");
  if (firstNewline >= 0 && body.slice(0, firstNewline).trim() === "") {
    body = body.slice(firstNewline + 1);
  }
  return body;
}

export async function sha256Hex(text: string): Promise<string> {
  const digest = await crypto.subtle.digest(
    "SHA-256",
    new TextEncoder().encode(text),
  );
  return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

export async function renderGenerated(prompt: string): Promise<string> {
  return [
    "// GENERATED by scripts/generate_base_prompt.ts — do not edit.",
    `// Source: ${DART_PROMPT_PATH} (${DART_CONSTANT})`,
    "// Regenerate with `deno task generate`; tests/prompt_parity_test.ts",
    "// fails if this file and the Dart source disagree.",
    "",
    `export const EDUBOT_BASE_PROMPT_SHA256 = "${await sha256Hex(prompt)}";`,
    "",
    `export const EDUBOT_BASE_PROMPT = ${JSON.stringify(prompt)};`,
    "",
  ].join("\n");
}

if (import.meta.main) {
  const source = await Deno.readTextFile(DART_PROMPT_PATH);
  const prompt = extractDartTripleQuoted(source, DART_CONSTANT);
  await Deno.writeTextFile(GENERATED_PATH, await renderGenerated(prompt));
  console.log(`wrote ${GENERATED_PATH} (${prompt.length} chars)`);
}
